### ISSUE TITLE
is it possible with dotlin to translate this postgresql driver written in pure kotlin to dart

### ISSUE THREAD

**Issue by insinfo** [dotlin-org/dotlin#2]
is it possible with dotlin to translate this postgresql driver written in pure kotlin to dart

https://github.com/jasync-sql/jasync-sql/tree/master/postgresql-async

**Comment by wilkomanger** [comment]
Hi, anything written for Kotlin/JVM (or Kotlin MPP) won't work with Dotlin. Dotlin aims to integrate Kotlin as a language into the Dart ecosystem.

However, this means that you'll be able to use _any_ Dart library directly in Dotlin, without writing your own wrapper or anything. For example, you'd be able to use Dart packages such as [postgres](https://pub.dev/packages/postgres) or [postgres2](https://pub.dev/packages/postgresql2) instead.

Hope that helps!
