### ISSUE TITLE
when() causes error when unnecessary else is missing

### ISSUE THREAD

**Issue by eggnstone** [dotlin-org/dotlin#74]
I have a `when()` which covers all cases and therefore has no `else` but dotlin throws an error:
```
Exception in thread "main" java.lang.IllegalArgumentException: Last branch in if/when expression must be else
```
Kotlin:
```
when (currentAreaType)
{
  SimpleAreaType.Instruction -> handleInstructionArea(c)
  SimpleAreaType.Unknown -> handleUnknownArea(c)
  SimpleAreaType.Whitespace -> handleWhitespaceArea(c)
  //else -> throwError("only necessary because of dotlin")
}
```
when I add the unnecessary `else` then I get a warning:
```
warning: 'when' is exhaustive so 'else' is redundant here
else -> throwError("only necessary because of dotlin")
^
```

**Comment by wilkomanger** [comment]
Could you post the full code including `SimpleAreaType`?

**Comment by eggnstone** [comment]
The whole code is probably too much but you can find it at https://github.com/eggnstone/DartFormatJetbrainsPlugin/blob/39f308699fa6d31154a86cfa27e0bfb90a50c775/src/main/kotlin/com/eggnstone/jetbrainsplugins/dartformat/simple_blockifier/SimpleBlockifier.kt
```
enum class SimpleAreaType
{
    Instruction,
    Unknown,
    Whitespace
}

```

**Comment by wilkomanger** [comment]
Thanks! Will look into it
